# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6041e3675fdb8b8dee4c0813e3fbea8af8ae582d52e50b05cb5d217ad3a949f12eadab5219fa38296860475eaa5cc7e86090f710a290b45d8361ab371c7cbfcc

test:
  secret_key_base: bc349233211a7abdacf201de828662a3a00566b17c8ecbc7fc5e45c0d2e7730497ea9fed6b3b1554a7c8c5cdbac41b9dec5d7099a3ed6023dd44a27611c273e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
